interval: 168 # hours
urls: # URLs of RSS feeds, put newsletters at the end
  - https://feeds.feedburner.com/brad-frosts-blog
  - https://joshcollinsworth.com/api/rss.xml
  - https://jvns.ca/atom.xml
  - https://leebyron.com/til/feed.xml
  - https://lynnandtonic.com/feed.xml
  - https://paularmstrong.dev/feed.xml
  - https://thesephist.com/index.xml
  - https://www.smashingmagazine.com/feed
  - https://www.swyx.io/rss.xml
  - https://www.taniarascia.com/rss.xml
