name: build and deploy

on:
  push:
    branches:
      - build
  schedule:
    - cron: '0 4 * * 2' # every Tuesday at 4AM

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: build

      - name: setup go
        uses: actions/setup-go@v4
        with:
          go-version: '1.18.0'

      - name: build
        run: go run -v ./cmd

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
