name: run

on:
  push:
    branches:
      - build
  # schedule:
  #   - cron: '0 4 * * 2' # every Tuesday at 4AM

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: build

      - name: setup go
        uses: actions/setup-go@v4
        with:
          go-version: '1.18.0'

      - name: run
        run: go run -v ./cmd ${{ secrets.DROPBOX }}
