name: run

on:
  push:
    branches:
      - build
  schedule:
    - cron: '0 4 * * 6' # every Saturday at 4AM

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: build

      - name: setup go
        uses: actions/setup-go@v4
        with:
          go-version: '1.18.0'

      - name: run
        run: go run -v ./cmd --dropboxAppKey=${{ secrets.DROPBOX_APP_KEY }} --dropboxAppSecret=${{ secrets.DROPBOX_APP_SECRET }} --dropboxRefreshToken=${{ secrets.DROPBOX_REFRESH_TOKEN }}
