name: release

on:
  push:
    tags:
      - 'v*.*.*'

env:
  PROJECT_NAME: dahlia
  GOOS: linux
  GOARCH: amd64

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup go
        uses: actions/setup-go@v4
        with:
          go-version: '1.18.0'

      - name: build
        run: |
          GOOS="${{ env.GOOS }}" GOARCH="${{ env.GOARCH }}" go build -v -ldflags="-s -w" -o "${{ env.PROJECT_NAME }}.${{ env.GOOS }}.${{ env.GOARCH }}" ./cmd

      - name: release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.PROJECT_NAME }}.${{ env.GOOS }}.${{ env.GOARCH }}
