name: run

on:
  schedule:
    - cron: "0 4 * * 6" # every Saturday at 4AM
      
env:
  PROJECT_NAME: anthology
  PROJECT_REPO: "kuosandys/anthology"
  TARGET_BRANCH: build

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: "${{ env.TARGET_BRANCH }}"

      - name: download release
        uses: jaxxstorm/action-install-gh-release@v1.10.0
        with:
          repo: "${{ env.PROJECT_REPO }}"
          extension-matching: disable
          rename-to: ${{ env.PROJECT_NAME }}
          chmod: 0755

      - name: run generate
        run: ${{ env.PROJECT_NAME }} --upload --dropboxAppKey=${{ secrets.DROPBOX_APP_KEY }} --dropboxAppSecret=${{ secrets.DROPBOX_APP_SECRET }} --dropboxRefreshToken=${{ secrets.DROPBOX_REFRESH_TOKEN }}
